const text = (name, title) => ({name, title, type: 'string'})
export default {
  name: 'submission',
  title: 'Customer enquiries',
  type: 'document',
  fields: [
    {...text('name', 'Full name'), readOnly: true},
    {...text('email', 'Email'), readOnly: true},
    {...text('phone', 'Phone'), readOnly: true},
    {...text('serviceInterested', 'Selected service'), readOnly: true},
    {...text('selectedCourse', 'Course ID'), readOnly: true},
    {...text('courseTitle', 'Course'), readOnly: true},
    {...text('counsellingSlug', 'Counselling service'), readOnly: true},
    {...text('source', 'Enquiry source'), readOnly: true},
    {...text('careerGoal', 'Career support'), readOnly: true},
    {...text('loanType', 'Financial assistance'), readOnly: true},
    {name: 'message', title: 'Message', type: 'text', readOnly: true},
    {
      name: 'status',
      title: 'Status',
      type: 'string',
      initialValue: 'new',
      options: {list: ['new', 'contacted', 'interested', 'converted', 'closed']},
    },
    text('owner', 'Assigned owner'),
    {name: 'submittedAt', title: 'Submitted at', type: 'datetime', readOnly: true},
    {name: 'termsAccepted', type: 'boolean', readOnly: true},
    text('consentVersion', 'Consent version'),
    {...text('notificationStatus', 'Notification status'), readOnly: true},
    ...['country', 'preferredDestination', 'interestedCourse', 'service'].map((name) => ({
      ...text(name, 'Legacy: ' + name),
      readOnly: true,
      hidden: ({document}) => !document?.[name],
    })),
  ],
  preview: {select: {title: 'name', subtitle: 'serviceInterested'}},
}
